# Github Actions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#

name: GitHubBuild


on:
 push:
  branches: [master]

jobs:
 build:
  strategy:
   matrix:
    version: [0.6.3]
    node-version: [12.x]
    os: [ubuntu-latest, windows-latest, macos-latest]
  
  name: Building on ${{ matrix.os }}
  runs-on: ${{ matrix.os }}

  steps:
  - uses: actions/checkout@v2
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
    with:
      node-version: ${{ matrix.node-version }}
  - name: Install NPM Dependency # 'npm ci' is same as 'npm install' but faster
    run: npm ci
#  - run: npm run lint
#  - run: npm run build --if-present
# Icons
  - name: Make Icons
    run: npm run electron:generate-icons
# Build
  - name: Build with Electron
    run: npm run electron:build

# Uploading the respective builds
# Linux -----------------------------------------
  - name: Upload .deb Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'ubuntu')
    with:
      name: invdo-0.6.3-amd64.deb
      path: dist_electron/invdo-0.6.3-amd64.deb

  - name: Upload .rpm Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'ubuntu')
    with:
      name: invdo-0.6.3-amd64.rpm
      path: dist_electron/invdo-0.6.3.x86-64.rpm

  - name: Upload AppImage Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'ubuntu')
    with:
      name: InVDO-0.6.3.AppImage
      path: dist_electron/InVDO-0.6.3.AppImage

  - name: Upload .snap Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'ubuntu')
    with:
      name: invdo_0.6.3_amd64.snap
      path: dist_electron/invdo_0.6.3_amd64.snap
  
#  - name: Upload Web Build
#    uses: actions/upload-artifact@v2
#    if: startsWith(matrix.os, 'ubuntu')
#    with:
#      name: invdo-0.1.0-static-web
#      path: dist/

# Windows -----------------------------------------
  - name: Upload Windows .zip Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'windows')
    with:
      name: invdo-0.6.3-win-x64-portable
      path: dist_electron/invdo-0.6.3-win.zip

  - name: Upload Windows .exe Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'windows')
    with:
      name: InVDO-${{ matrix.version }}-setup-x64.exe
      path: dist_electron/invdo Setup ${{ matrix.version }}.exe
# MAC ----------------------------------------------
  - name: Upload Mac .zip Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'macos')
    with:
      name: InVDO-0.6.3-mac.zip
      path: dist_electron/InVDO-0.6.3-mac.zip

  - name: Upload Mac .dmg Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'macos')
    with:
      name: InVDO-0.6.3.dmg
      path: dist_electron/InVDO-0.6.3.dmg
