# Github Actions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#

name: GitHubBuild

on:
 push:
  branches: [master]

jobs:
 build:
  strategy:
   matrix:
    node-version: [12.x]
    os: [ubuntu-latest, windows-latest, macos-latest]
  
  name: Building on ${{ matrix.os }}
  runs-on: ${{ matrix.os }}

  steps:
  - uses: actions/checkout@v2
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
    with:
      node-version: ${{ matrix.node-version }}
  - run: npm ci
#  - run: npm run lint
#  - run: npm run build --if-present
  - run: npm run electron:build
  - name: Upload .deb Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'ubuntu')
    with:
      name: invdo-0.1.0-amd64.deb
      path: dist_electron/invdo-0.1.0-amd64.deb
  - name: Upload AppImage Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'ubuntu')
    with:
      name: invdo-0.1.0-amd64.AppImage
      path: dist_electron/invdo-0.1.0.AppImage
  - name: Upload .rpm Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'ubuntu')
    with:
      name: invdo-0.1.0-amd64.rpm
      path: dist_electron/invdo-0.1.0.x86-64.rpm
  - name: Upload Web Build
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'ubuntu')
    with:
      name: invdo-0.1.0-static-web
      path: dist/
  - name: Upload Windows .exe Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'windows')
    with:
      name: invdo-0.1.0-win-x64-portable
      path: dist_electron/invdo-0.1.0-win.zip
  - name: Upload Windows .zip Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'windows')
    with:
      name: invdo-0.1.0-setup-x64.exe
      path: dist_electron/invdo Setup 0.1.0.exe
  - name: Upload Mac .dmg Artifact
    uses: actions/upload-artifact@v2
    if: startsWith(matrix.os, 'macos')
    with:
      name: invdo-0.1.0-mac.dmg
      path: dist_electron/invdo-0.1.0.dmg
